AWSTemplateFormatVersion: "2010-09-09"
# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------#
Parameters:
#VPCID
  VpcId:
    Description : "VPC ID"
    Type: AWS::EC2::VPC::Id

#SG Allow CidrBlock
  CidrBlock:
    Description: Please type the CidrBlock allows SG.
    Type: String

#InterfaceEndpointSubnet
  InterfaceEndpointSubnet:
    Description : "Interface Endpoint Subnet"
    Type : AWS::EC2::Subnet::Id

#GatewayEndpointRoutetable
  GatewayEndpointRoutetable:
    Description : "Gateway Endpoint Routetable"
    Type : AWS::EC2::RouteTable::Id



Resources:
# ------------------------------------------------------------#
# Create SG
# ------------------------------------------------------------#
  SsmEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "ssm-edp-sg"
      GroupName: ssm-edp-sg
      SecurityGroupIngress:
        IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: !Sub ${CidrBlock}
      VpcId: !Ref VpcId
  EC2MessagesEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "ec2messages-edp-sg"
      GroupName: ec2messages
      SecurityGroupIngress:
        IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: !Sub ${CidrBlock}
      VpcId: !Ref VpcId
  SsmMessagesEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "ssmmessages-edp-sg"
      GroupName: ssmmessages-edp-sg
      SecurityGroupIngress:
        IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: !Sub ${CidrBlock}
      VpcId: !Ref VpcId
# ------------------------------------------------------------#
# Create ssm End Point
# ------------------------------------------------------------#
  SsmEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: com.amazonaws.ap-northeast-1.ssm
      SubnetIds: 
        - !Ref InterfaceEndpointSubnet
      VpcId: !Ref VpcId
      VpcEndpointType: Interface
      SecurityGroupIds: 
        - !Ref SsmEndpointSecurityGroup
      PrivateDnsEnabled: true
  EC2MessagesEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: com.amazonaws.ap-northeast-1.ec2messages
      SubnetIds: 
        - !Ref InterfaceEndpointSubnet
      VpcId: !Ref VpcId
      VpcEndpointType: Interface
      SecurityGroupIds: 
        - !Ref EC2MessagesEndpointSecurityGroup
      PrivateDnsEnabled: true
  SsmMessagesEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: com.amazonaws.ap-northeast-1.ssmmessages
      SubnetIds: 
        - !Ref InterfaceEndpointSubnet
      VpcId: !Ref VpcId
      VpcEndpointType: Interface
      SecurityGroupIds: 
        - !Ref SsmMessagesEndpointSecurityGroup
      PrivateDnsEnabled: true
  S3MessagesEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: com.amazonaws.ap-northeast-1.s3
      RouteTableIds: 
        - !Ref GatewayEndpointRoutetable
      VpcId: !Ref VpcId
      VpcEndpointType: Gateway
